version: '3.8'

networks: 
  nginx_network:
    external: true
  metabase_network:

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment: 
      - JAVA_OPTS=-Xmx300m
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_EMAIL_FROM_ADDRESS=${MB_EMAIL_FROM_ADDRESS}
      - MB_EMAIL_SMTP_HOST=${MB_EMAIL_SMTP_HOST}
      - MB_EMAIL_SMTP_PASSWORD=${MB_EMAIL_SMTP_PASSWORD}
      - MB_EMAIL_SMTP_PORT=${MB_EMAIL_SMTP_PORT}
      - MB_EMAIL_SMTP_SECURIT=${MB_EMAIL_SMTP_SECURIT}
      - MB_EMAIL_SMTP_USERNAME=${MB_EMAIL_SMTP_USERNAME}
    volumes: 
      - ./volumes/metabase:/metabase-data
    networks: 
      - metabase_network
      - nginx_network
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    networks: 
      - metabase_network