version: '3.8'

networks: 
  metabase-network:

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment: 
      - JAVA_OPTS=-Xmx300m
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes: 
      - ./volumes/metabase:/metabase-data
    networks: 
      - metabase-network
    ports:
      - 3000:3000
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    networks: 
      - metabase-network